deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_HUB_ACCESS_TOKEN
  target_branch: master
  on:
    branch: develop
  local_dir: public
env:
  global:
  - secure: L4WRCEetY3eLCuLbBkNi+xWjUFOg0pcPbWgdvMkW33H+PQ0IBVySIRmX+WgV4wQOkJcDmCSSzuF52JR7cQmmg+qkz/CF6/OJJL9XYxBiNVcqu/wGkBObmvdI8fyZGu9cEG22ZviPDmB2wATm3qKwCANLtrRM0B8RTSGw45L6sPQpF5OSg0IKqbV+92Nr820ybnDi6G4fQ+DkXM/UJN7rrCKAYRTiNCjRO/SH7wL80WCJoOPmWW5x/dq+o/3+KgFmUGWgQr0HVjKnY8vnU1pvC1ml64AidXh1229GKsKLmCfo+W6NBjSooncvfLwkVAj5VL6itH4bfEw0EdbGBoQZ3cQtX2rd677KGPf9OIAS/dMMpiIHy9RjZtUKvW5z2F1npMC/RAXCv12ZjFa594RTuvGaGX18v7h3LUirJ+MbRiVSzORXq79CS4JKdAJZEcFJm1FuTqlCOUi/GGaGnO21iLIQjfnUwWYmZeDorupOkHMbtDvSEV9UbWJrUSzsv/9X/0r8UVayxI4vHkP7FqmkBxSIq3T/l6aRiCI8XREIevyXy/MJTk+6WpLlWsHIxcatSsFZrSI58Pb7cB4TOQ+PKgkAe+uAAGlh/6K6WQ31dh2ZnHjgBOpL8Mk1iuoy7MO46ckLu7ySp+vYZoGGWi4P57ZhR6gl1rVTFywcXiR0H4s=
language: node_js
node_js: 9
script: gatsby build
sudo: false
